export const AUTH_TRY = 'AUTH_TRY';
export const AUTH_UPDATE_DATA = 'AUTH_UPDATE_DATA';
export const AUTH_UPDATE_TOKEN = 'AUTH_UPDATE_TOKEN';
export const AUTH_UPDATE_TOKEN_STORAGE = 'AUTH_UPDATE_TOKEN_STORAGE';
export const AUTH_CLEAR_DATA = 'AUTH_CLEAR_DATA';
export const AUTH_TRY_AUTO = 'AUTH_TRY_AUTO';
export const AUTH_TOGGLE_LOADING = 'AUTH_TOGGLE_LOADING';
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';

export const TRANSACTIONS_FETCH = 'TRANSACTIONS_FETCH';
export const TRANSACTIONS_STORE_ALL = 'TRANSACTIONS_STORE_ALL';
export const TRANSACTIONS_NEW = 'TRANSACTIONS_NEW';

export const WALLETS_FETCH = 'WALLETS_FETCH';
export const WALLETS_STORE = 'WALLETS_STORE';
export const WALLETS_FETCH_BALLANCE = 'WALLETS_FETCH_BALLANCE'
export const WALLETS_FETCH_BALLANCE_SUCCESS = 'WALLETS_FETCH_BALLANCE_SUCCESS'
